package javaapplication2;
//import java.awt.Color;
//import java.awt.Font;
//import java.awt.event.*;
//import java.sql.Connection;
//import java.sql.DriverManager;
//import java.sql.ResultSet;
//import java.sql.SQLException;
//import java.sql.Statement;
import java.util.Calendar;
import java.util.TimeZone;


public class ChoiceButtons extends javax.swing.JFrame {
    
    /**
     * Creates new form ChoiceButtons
     */

	boolean restart;
	public String user,sDate;
	Calendar c= Calendar.getInstance(TimeZone.getTimeZone("GMT"));
	public float res,num1=0;
	
    public void change()
	{
		String query1="update userdata set balance="+LoginPage.bal+"where username='"+LoginPage.user+"'";
                String query2="select email from userdata where username='"+LoginPage.user+"'";
		int rows_updated;
		try {
			rows_updated = LoginPage.st.executeUpdate(query1);
			System.out.println("Rows updated are: "+rows_updated);
                        LoginPage.st.executeUpdate(query1);
		} catch (java.sql.SQLException e) {
			e.printStackTrace();
		}
	}
    
    
    public ChoiceButtons() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Deposit = new javax.swing.JButton();
        Header = new javax.swing.JLabel();
        Balance_inquiry = new javax.swing.JButton();
        PIN_change = new javax.swing.JButton();
        Money_transfer = new javax.swing.JButton();
        Exit = new javax.swing.JButton();
        Withdrawal = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Deposit.setBackground(new java.awt.Color(0, 51, 255));
        Deposit.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        Deposit.setForeground(new java.awt.Color(255, 255, 255));
        Deposit.setText("Deposit");
        Deposit.setToolTipText("Click to Deposit Money");
        Deposit.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray));
        Deposit.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Deposit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DepositActionPerformed(evt);
            }
        });

        Header.setBackground(new java.awt.Color(0, 204, 153));
        Header.setFont(new java.awt.Font("Engravers MT", 1, 18)); // NOI18N
        Header.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Header.setText("Welcome To SBM");
        Header.setToolTipText("");
        Header.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Header.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Header.setDoubleBuffered(true);
        Header.setName(""); // NOI18N

        Balance_inquiry.setBackground(new java.awt.Color(0, 51, 255));
        Balance_inquiry.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        Balance_inquiry.setForeground(new java.awt.Color(255, 255, 255));
        Balance_inquiry.setText("Balance Inquiry");
        Balance_inquiry.setToolTipText("Click to know available balance");
        Balance_inquiry.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray));
        Balance_inquiry.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Balance_inquiry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Balance_inquiryActionPerformed(evt);
            }
        });

        PIN_change.setBackground(new java.awt.Color(0, 51, 255));
        PIN_change.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        PIN_change.setForeground(new java.awt.Color(255, 255, 255));
        PIN_change.setText("PIN Change");
        PIN_change.setToolTipText("Click here to change your pin");
        PIN_change.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray));
        PIN_change.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        PIN_change.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PIN_changeActionPerformed(evt);
            }
        });

        Money_transfer.setBackground(new java.awt.Color(0, 51, 255));
        Money_transfer.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        Money_transfer.setForeground(new java.awt.Color(255, 255, 255));
        Money_transfer.setText("Money Transfer");
        Money_transfer.setToolTipText("Click to Transfer money");
        Money_transfer.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray));
        Money_transfer.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Money_transfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Money_transferActionPerformed(evt);
            }
        });

        Exit.setBackground(new java.awt.Color(0, 51, 255));
        Exit.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        Exit.setForeground(new java.awt.Color(255, 255, 255));
        Exit.setText("Exit");
        Exit.setToolTipText("Click here to exit");
        Exit.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray));
        Exit.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });

        Withdrawal.setBackground(new java.awt.Color(0, 51, 255));
        Withdrawal.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        Withdrawal.setForeground(new java.awt.Color(255, 255, 255));
        Withdrawal.setText("Withdrawal");
        Withdrawal.setToolTipText("Click to Withdraw Money");
        Withdrawal.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray));
        Withdrawal.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Withdrawal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WithdrawalActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        jLabel1.setText("SBM ©");
        jLabel1.setToolTipText("Copyright");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Deposit, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Balance_inquiry, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Money_transfer, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 361, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PIN_change, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Exit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Withdrawal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addComponent(Header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Header, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Deposit, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Withdrawal, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Balance_inquiry, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PIN_change, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Money_transfer, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 154, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DepositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DepositActionPerformed
        new Deposit().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_DepositActionPerformed

    private void Balance_inquiryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Balance_inquiryActionPerformed
        javax.swing.JOptionPane.showMessageDialog(rootPane, "Under Development!!!!", "Access Denied", getDefaultCloseOperation());
    }//GEN-LAST:event_Balance_inquiryActionPerformed

    private void PIN_changeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PIN_changeActionPerformed
       new PIN_Change().setVisible(true);
       this.dispose();
    }//GEN-LAST:event_PIN_changeActionPerformed

    private void Money_transferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Money_transferActionPerformed
        new MoneyTransfer().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Money_transferActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
            System.err.println("Session was closed ");
            System.exit(0);
    }//GEN-LAST:event_ExitActionPerformed

    private void WithdrawalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WithdrawalActionPerformed
        new Withdrawal().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_WithdrawalActionPerformed

    /**
     * @param args the command line arguments
     */
   /* public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
       /* try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChoiceButtons.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChoiceButtons.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChoiceButtons.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChoiceButtons.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
       /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChoiceButtons().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Balance_inquiry;
    private javax.swing.JButton Deposit;
    private javax.swing.JButton Exit;
    private javax.swing.JLabel Header;
    private javax.swing.JButton Money_transfer;
    private javax.swing.JButton PIN_change;
    private javax.swing.JButton Withdrawal;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
