package javaapplication2;


import java.awt.Color;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Calendar;
import java.util.TimeZone;
import static javaapplication2.LoginPage.st;

public class MoneyTransfer extends javax.swing.JFrame {
    ChoiceButtons obj_MT=new ChoiceButtons();
    Calendar c= Calendar.getInstance(TimeZone.getTimeZone("GMT"));
    static float bal_payee=0;
    /**
     * Creates new form NewJFrame
     */
    public MoneyTransfer() {
        initComponents();
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Transfer_label = new javax.swing.JLabel();
        Payee = new javax.swing.JTextField();
        Amount_label = new javax.swing.JLabel();
        Amount = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Transfer = new javax.swing.JButton();
        Cancel = new javax.swing.JButton();
        Reset = new javax.swing.JButton();
        Header = new javax.swing.JLabel();
        Back = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Transfer_label.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        Transfer_label.setForeground(new java.awt.Color(255, 255, 255));
        Transfer_label.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Transfer_label.setText("Transfer To :");

        Payee.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        Payee.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Payee.setText("Enter the Username");
        Payee.setToolTipText("Please enter the username");
        Payee.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        Payee.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                PayeeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                PayeeFocusLost(evt);
            }
        });

        Amount_label.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        Amount_label.setForeground(new java.awt.Color(255, 255, 255));
        Amount_label.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Amount_label.setText("Amount :");

        Amount.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        Amount.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Amount.setText("Enter the amount");
        Amount.setToolTipText("Enter the amount to be transferred");
        Amount.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        Amount.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                AmountFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                AmountFocusLost(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("SADA ©");
        jLabel3.setToolTipText("Copyright");

        Transfer.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        Transfer.setText("Transfer");
        Transfer.setToolTipText("Click here to transfer");
        Transfer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TransferMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TransferMouseExited(evt);
            }
        });
        Transfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TransferActionPerformed(evt);
            }
        });

        Cancel.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        Cancel.setText("Cancel");
        Cancel.setToolTipText("Click here to cancel the transaction");
        Cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CancelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CancelMouseExited(evt);
            }
        });
        Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelActionPerformed(evt);
            }
        });

        Reset.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        Reset.setText("Reset");
        Reset.setToolTipText("Click here to reset the values");
        Reset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ResetMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ResetMouseExited(evt);
            }
        });
        Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetActionPerformed(evt);
            }
        });

        Header.setBackground(new java.awt.Color(0, 204, 153));
        Header.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        Header.setForeground(new java.awt.Color(255, 255, 255));
        Header.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Header.setText("Welcome To SADA");
        Header.setToolTipText("");
        Header.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Header.setDoubleBuffered(true);
        Header.setName(""); // NOI18N

        Back.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        Back.setText("Back");
        Back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BackMouseExited(evt);
            }
        });
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Devendra M Naik\\Desktop\\back3.jpg")); // NOI18N
        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(210, 210, 210)
                .addComponent(Transfer_label, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(Payee, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(210, 210, 210)
                .addComponent(Back, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(193, 193, 193)
                .addComponent(Transfer, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(582, 582, 582)
                .addComponent(Reset, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(883, 883, 883)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(210, 210, 210)
                .addComponent(Cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(210, 210, 210)
                .addComponent(Amount_label, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(389, 389, 389)
                .addComponent(Amount, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(Header, javax.swing.GroupLayout.PREFERRED_SIZE, 940, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 940, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Transfer_label, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Payee, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(158, 158, 158)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Back, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Transfer, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(Reset, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(523, 523, 523)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(414, 414, 414)
                .addComponent(Cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(252, 252, 252)
                .addComponent(Amount_label, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(252, 252, 252)
                .addComponent(Amount, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(Header, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PayeeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PayeeFocusGained
        if(Payee.getText().equals("Enter the Username")){
            Payee.setText("");
            Payee.setBackground(Color.decode("#74c11d"));
        }
    }//GEN-LAST:event_PayeeFocusGained

    private void PayeeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PayeeFocusLost
        if(Payee.getText().trim().equals("")){
            Payee.setText("Enter the Username");
            Payee.setBackground(Color.decode("#ffffff"));
        }
    }//GEN-LAST:event_PayeeFocusLost

    private void AmountFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_AmountFocusGained
        if(Amount.getText().equals("Enter the amount")){
            Amount.setText("");
            Amount.setBackground(Color.decode("#74c11d"));
        }
    }//GEN-LAST:event_AmountFocusGained

    private void AmountFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_AmountFocusLost
        if(Amount.getText().trim().equals("")){
            Amount.setText("Enter the amount");
            Amount.setBackground(Color.decode("#ffffff"));
        }
    }//GEN-LAST:event_AmountFocusLost

    private void CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelActionPerformed
        System.out.println("Activity was cancelled by the user");
        System.exit(0);
    }//GEN-LAST:event_CancelActionPerformed

    private void TransferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TransferActionPerformed
        if( Payee.equals("Enter the Username") || Amount.getText().equals("Enter the amount") )
        {
            javax.swing.JOptionPane.showMessageDialog(rootPane, "Field cannot be blank", "Error in Money Transfer", getDefaultCloseOperation());
        }
        else
        {
            if(Integer.parseInt(Amount.getText().trim())>0 && Integer.parseInt(Amount.getText().trim())<LoginPage.bal && Payee.getText().trim().matches("[a-z]+") && Amount.getText().trim().matches("[0-9]+"))
            {
                String query1="select balance from userdata where username='"+Payee.getText().trim()+"'";
                String query2="update userdata set balance="+((LoginPage.bal)-(Integer.parseInt(Amount.getText().trim())))+" where username='"+LoginPage.user+"'";
                String query3="update userdata set balance="+(MoneyTransfer.bal_payee+Integer.parseInt(Amount.getText().trim()))+" where username='"+Payee.getText().trim()+"'";
                String query4="commit";
                try 
                {
                    LoginPage.con.setAutoCommit(false);
                    java.sql.ResultSet rs= st.executeQuery(query1);
                    rs.absolute(1);
                    MoneyTransfer.bal_payee=rs.getFloat("BALANCE");
                    LoginPage.st.executeUpdate(query2);
                    LoginPage.st.executeUpdate(query3);
                    LoginPage.con.setAutoCommit(true);
                    LoginPage.st.executeUpdate(query4); 
                }
                catch (java.sql.SQLException e)
                {
                    e.printStackTrace();
                }
                javax.swing.JOptionPane.showMessageDialog(rootPane, "Transaction Successfull", "Success", getDefaultCloseOperation());
                String sDate = Calendar.getInstance().get(Calendar.YEAR) + "-" 
							+ (Calendar.getInstance().get(Calendar.MONTH)+1)
							+ "-" + Calendar.getInstance().get(Calendar.DAY_OF_MONTH) 
							+ " at " + Calendar.getInstance().get(Calendar.HOUR_OF_DAY) 
							+ ":" + Calendar.getInstance().get(Calendar.MINUTE)+ ":" + Calendar.getInstance().get(Calendar.SECOND)+ ":" + Calendar.getInstance().get(Calendar.MILLISECOND);
                try(BufferedWriter bw = new BufferedWriter(new FileWriter(LoginPage.trans_details,true)))
                {
                    bw.append("Username: "+LoginPage.user+" transferred amount: "+Integer.parseInt(Amount.getText().trim())+" to "+Payee.getText().trim()+" on "+sDate);
                    bw.newLine();
                }
                catch(IOException e)
                {
                    e.printStackTrace();
                }
                new ChoiceButtons().setVisible(true);
                this.dispose();
            }
            else
            {
                    javax.swing.JOptionPane.showMessageDialog(rootPane, "Invalid credentials", "Error Deposit", getDefaultCloseOperation());
            }
        }
    }//GEN-LAST:event_TransferActionPerformed

    private void ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetActionPerformed
        Amount.setText("Enter the amount");
        Payee.setText("Enter the Username");
    }//GEN-LAST:event_ResetActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        new ChoiceButtons().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BackActionPerformed

    private void BackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackMouseEntered
        Back.setBackground(Color.decode("#2cdd9c"));
    }//GEN-LAST:event_BackMouseEntered

    private void BackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackMouseExited
        Back.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_BackMouseExited

    private void TransferMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TransferMouseEntered
        Transfer.setBackground(Color.GREEN);
    }//GEN-LAST:event_TransferMouseEntered

    private void TransferMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TransferMouseExited
        Transfer.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_TransferMouseExited

    private void ResetMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ResetMouseEntered
        Reset.setBackground(Color.decode("#2cdd9c"));
    }//GEN-LAST:event_ResetMouseEntered

    private void ResetMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ResetMouseExited
        Reset.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_ResetMouseExited

    private void CancelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelMouseEntered
        Cancel.setBackground(Color.red);
    }//GEN-LAST:event_CancelMouseEntered

    private void CancelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelMouseExited
        Cancel.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_CancelMouseExited

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Amount;
    private javax.swing.JLabel Amount_label;
    private javax.swing.JButton Back;
    private javax.swing.JButton Cancel;
    private javax.swing.JLabel Header;
    private javax.swing.JTextField Payee;
    private javax.swing.JButton Reset;
    private javax.swing.JButton Transfer;
    private javax.swing.JLabel Transfer_label;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
