package javaapplication2;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Timer;
import newpackage.MiniStatementGen;
import newpackage.SendMail;

public class PIN_Change extends javax.swing.JFrame {

    /**
     * Creates new form PIN_Change
     */
      Timer t;
    final int waitingTime = 4 * 70 * 1000;
        int c1=0;
        int f=1;
        final int delay = waitingTime / 1000;
        String sDate = Calendar.getInstance().get(Calendar.YEAR) + "-" + (Calendar.getInstance().get(Calendar.MONTH) + 1)
			+ "-" + Calendar.getInstance().get(Calendar.DAY_OF_MONTH) + " at "
			+ Calendar.getInstance().get(Calendar.HOUR_OF_DAY) + ":" + Calendar.getInstance().get(Calendar.MINUTE) + ":"
			+ Calendar.getInstance().get(Calendar.SECOND) + ":" + Calendar.getInstance().get(Calendar.MILLISECOND);
    public PIN_Change() {
        initComponents();
        t = new Timer(delay, new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e)
            {
                if(c1 <= 100){
                    jProgressBar1.setValue(++c1);
                    if(c1==10)
                        jProgressBar1.setString("Contacting the server");
                    if(c1==45)
                        jProgressBar1.setString("Please wait");
                    if(c1==99)
                       f=0;
                }
            }
        });
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Old_Pin_label = new javax.swing.JLabel();
        New_Pin_label = new javax.swing.JLabel();
        Change_PIN = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Old_PIN = new javax.swing.JPasswordField();
        New_PIN = new javax.swing.JPasswordField();
        Reset = new javax.swing.JButton();
        Copyright = new javax.swing.JLabel();
        Header = new javax.swing.JLabel();
        Back = new javax.swing.JButton();
        Cancel = new javax.swing.JButton();
        jProgressBar1 = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Old_Pin_label.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        Old_Pin_label.setForeground(new java.awt.Color(255, 255, 255));
        Old_Pin_label.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Old_Pin_label.setText("Old PIN :");
        Old_Pin_label.setToolTipText("");

        New_Pin_label.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        New_Pin_label.setForeground(new java.awt.Color(255, 255, 255));
        New_Pin_label.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        New_Pin_label.setText("New PIN :");

        Change_PIN.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        Change_PIN.setText("Change PIN");
        Change_PIN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Change_PINMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Change_PINMouseExited(evt);
            }
        });
        Change_PIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Change_PINActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Devendra M Naik\\Desktop\\back3.jpg")); // NOI18N
        jLabel1.setText("jLabel1");

        Old_PIN.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        Old_PIN.setText("Enter your Old PIN");
        Old_PIN.setToolTipText("Please enter your Old PIN");
        Old_PIN.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        Old_PIN.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Old_PINFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Old_PINFocusLost(evt);
            }
        });

        New_PIN.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        New_PIN.setText("Enter your New PIN");
        New_PIN.setToolTipText("Please enter your New PIN");
        New_PIN.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        New_PIN.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                New_PINFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                New_PINFocusLost(evt);
            }
        });

        Reset.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        Reset.setText("Reset");
        Reset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ResetMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ResetMouseExited(evt);
            }
        });
        Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetActionPerformed(evt);
            }
        });

        Copyright.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        Copyright.setText("SADA ©");

        Header.setBackground(new java.awt.Color(0, 204, 153));
        Header.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        Header.setForeground(new java.awt.Color(255, 255, 255));
        Header.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Header.setText("Welcome To SADA");
        Header.setToolTipText("");
        Header.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Header.setDoubleBuffered(true);
        Header.setName(""); // NOI18N

        Back.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        Back.setText("Back");
        Back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BackMouseExited(evt);
            }
        });
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        Cancel.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        Cancel.setText("Cancel");
        Cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CancelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CancelMouseExited(evt);
            }
        });
        Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelActionPerformed(evt);
            }
        });

        jProgressBar1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jProgressBar1.setString("");
        jProgressBar1.setStringPainted(true);
        jProgressBar1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jProgressBar1StateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Header, javax.swing.GroupLayout.PREFERRED_SIZE, 940, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(220, 220, 220)
                .addComponent(Old_Pin_label, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(Old_PIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(220, 220, 220)
                .addComponent(New_Pin_label, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(New_PIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(Back, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(314, 314, 314)
                .addComponent(Change_PIN, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(Cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 940, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(890, 890, 890)
                .addComponent(Copyright, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(660, 660, 660)
                .addComponent(Reset, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 940, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(Header, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Old_Pin_label, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Old_PIN, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(New_Pin_label, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(New_PIN, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Back, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Change_PIN, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addComponent(Cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Copyright, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(390, 390, 390)
                .addComponent(Reset, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 537, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Old_PINFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Old_PINFocusGained
        if(new String(Old_PIN.getPassword()).equals("Enter your Old PIN")){
            Old_PIN.setText("");
            Old_PIN.setBackground(Color.decode("#74c11d"));
        }
    }//GEN-LAST:event_Old_PINFocusGained

    private void Old_PINFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Old_PINFocusLost
        if(new String(Old_PIN.getPassword()).trim().equals("")){
            Old_PIN.setText("Enter your Old PIN");
            Old_PIN.setBackground(Color.decode("#ffffff"));
        }
    }//GEN-LAST:event_Old_PINFocusLost

    private void New_PINFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_New_PINFocusGained
        if(new String(New_PIN.getPassword()).equals("Enter your New PIN")){
            New_PIN.setText("");
            New_PIN.setBackground(Color.decode("#74c11d"));
        }
    }//GEN-LAST:event_New_PINFocusGained

    private void New_PINFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_New_PINFocusLost
        if(new String(New_PIN.getPassword()).trim().equals("")){
            New_PIN.setText("Enter your New PIN");
            New_PIN.setBackground(Color.decode("#ffffff"));
        }
    }//GEN-LAST:event_New_PINFocusLost

    private void ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetActionPerformed
        Old_PIN.setText("Enter your Old PIN");
        New_PIN.setText("Enter your New PIN");
    }//GEN-LAST:event_ResetActionPerformed

    private void Change_PINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Change_PINActionPerformed
         String pass1=new String(Old_PIN.getPassword()).trim();
         String pass2=new String(New_PIN.getPassword()).trim();
         int row;
         if(pass1.equals("Enter your Old PIN")||pass2.equals("Enter your New PIN"))
         {
             javax.swing.JOptionPane.showMessageDialog(rootPane, "Field cannot be left blank.", "Error", getDefaultCloseOperation());
         }
         else
         {
            if(pass1.matches("[0-9]+")||pass2.matches("[0-9]+"))
            {
                if(pass1.equals(pass2))
                {
                   javax.swing.JOptionPane.showMessageDialog(rootPane, "Old PIN and New PIN is same", "Error Same PIN", getDefaultCloseOperation());
                }
                else
                {
                   if(Integer.parseInt(pass1)==LoginPage.pin)
                   {
                       try {
                           row=LoginPage.st.executeUpdate("update userdata set pin="+Integer.parseInt(pass2)+" where username='"+LoginPage.user+"'");
                       } catch (SQLException ex) {
                           Logger.getLogger(PIN_Change.class.getName()).log(Level.SEVERE, null, ex);
                       }
                       //javax.swing.JOptionPane.showMessageDialog(rootPane, "PIN was changed successfully!\nPlease do remember your New PIN", "Success", getDefaultCloseOperation());
                       //String str = "A PIN change has been made using your Debit Card linked to SAAD Bank Account on " + sDate + ".";
					new MiniStatementGen(LoginPage.user,"PIN CHANGED", 0, LoginPage.bal); //Start Ministatement Generation Thread
					//new SendMail(LoginPage.email, "PIN CHANGED", 0); //Start Mail Sending Thread
					t.start();
					System.out.println(" Your Debit Card PIN was changed on " + sDate);
                   }
                   else
                   {
                       javax.swing.JOptionPane.showMessageDialog(rootPane, "You have entered wrong credentials", "Error", getDefaultCloseOperation());
                   }
                }
            }
            else
                javax.swing.JOptionPane.showMessageDialog(rootPane, "You have entered wrong credentials", "Error", getDefaultCloseOperation());
        }        
    }//GEN-LAST:event_Change_PINActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        new ChoiceButtons().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BackActionPerformed

    private void CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelActionPerformed
        System.out.println("Session closed");
        System.exit(0);
    }//GEN-LAST:event_CancelActionPerformed

    private void jProgressBar1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jProgressBar1StateChanged
        if(f==0)
        {
            new ChoiceButtons().setVisible(true);
            this.dispose();
            javax.swing.JOptionPane.showMessageDialog(rootPane, "PIN Changed successfully", "Success",getDefaultCloseOperation());
        }
    }//GEN-LAST:event_jProgressBar1StateChanged

    private void BackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackMouseEntered
        Back.setBackground(Color.decode("#2cdd9c"));
    }//GEN-LAST:event_BackMouseEntered

    private void BackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackMouseExited
        Back.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_BackMouseExited

    private void Change_PINMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Change_PINMouseEntered
        Change_PIN.setBackground(Color.GREEN);
    }//GEN-LAST:event_Change_PINMouseEntered

    private void Change_PINMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Change_PINMouseExited
        Change_PIN.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_Change_PINMouseExited

    private void CancelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelMouseEntered
        Cancel.setBackground(Color.red);
    }//GEN-LAST:event_CancelMouseEntered

    private void CancelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelMouseExited
        Cancel.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_CancelMouseExited

    private void ResetMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ResetMouseEntered
        Reset.setBackground(Color.decode("#2cdd9c"));
    }//GEN-LAST:event_ResetMouseEntered

    private void ResetMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ResetMouseExited
        Reset.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_ResetMouseExited

    /**
     * @param args the command line arguments
     */
    /*public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
/*        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PIN_Change.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PIN_Change.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PIN_Change.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PIN_Change.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
       /* java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PIN_Change().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton Cancel;
    private javax.swing.JButton Change_PIN;
    private javax.swing.JLabel Copyright;
    private javax.swing.JLabel Header;
    private javax.swing.JPasswordField New_PIN;
    private javax.swing.JLabel New_Pin_label;
    private javax.swing.JPasswordField Old_PIN;
    private javax.swing.JLabel Old_Pin_label;
    private javax.swing.JButton Reset;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables
}
