package admin_pack;
import java.sql.SQLException;
import javaapplication2.LoginPage;
import java.util.concurrent.ThreadLocalRandom;
import java.util.logging.Level;
import java.util.logging.Logger;

public class Create_User extends javax.swing.JFrame {

    /**
     * Creates new form Create_User
     */
    public Create_User() {
        initComponents();
    }
    public String user,email;
    public Integer bal;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Username_text = new javax.swing.JTextField();
        PIN_text = new javax.swing.JTextField();
        Balance_text = new javax.swing.JTextField();
        Create_User = new javax.swing.JButton();
        Cancel = new javax.swing.JButton();
        Back = new javax.swing.JButton();
        Reset = new javax.swing.JButton();
        Email_text = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Username :");

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Password :");

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Balance :");

        Username_text.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        Username_text.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Username_text.setText("Enter Username");
        Username_text.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Username_textFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Username_textFocusLost(evt);
            }
        });
        Username_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Username_textActionPerformed(evt);
            }
        });

        PIN_text.setEditable(false);
        PIN_text.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        PIN_text.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        PIN_text.setText("Enter Password");
        PIN_text.setToolTipText("System generated password");
        PIN_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PIN_textActionPerformed(evt);
            }
        });

        Balance_text.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        Balance_text.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Balance_text.setText("Enter Balance");
        Balance_text.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Balance_textFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Balance_textFocusLost(evt);
            }
        });
        Balance_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Balance_textActionPerformed(evt);
            }
        });

        Create_User.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        Create_User.setText("Create User");
        Create_User.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Create_UserActionPerformed(evt);
            }
        });

        Cancel.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        Cancel.setText("Cancel");
        Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelActionPerformed(evt);
            }
        });

        Back.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        Reset.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        Reset.setText("Reset");
        Reset.setToolTipText("Click here to Reset the values");
        Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetActionPerformed(evt);
            }
        });

        Email_text.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        Email_text.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Email_text.setText("Enter email");
        Email_text.setToolTipText("Please enter your email");
        Email_text.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Email_textFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Email_textFocusLost(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Email :");
        jLabel4.setToolTipText("Email Label");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(207, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Back, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(147, 147, 147)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Reset, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Create_User, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(150, 150, 150))
            .addGroup(layout.createSequentialGroup()
                .addGap(255, 255, 255)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(79, 79, 79)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Email_text, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(Username_text, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                        .addComponent(PIN_text)
                        .addComponent(Balance_text)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Username_text, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Email_text, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PIN_text, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Balance_text, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE))
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Back, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Reset, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Create_User, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelActionPerformed
        System.out.println("Session closed by admin");
        System.exit(0);
    }//GEN-LAST:event_CancelActionPerformed

    private void Create_UserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Create_UserActionPerformed
        if(Username_text.getText().equals("Enter Username")||Balance_text.getText().equals("Enter Balance")||Email_text.getText().equals("Enter email"))
        {
            javax.swing.JOptionPane.showMessageDialog(rootPane, "Field cannot be left blank.", "Error", getDefaultCloseOperation());
        }
        else
        {
            user=Username_text.getText();
            bal=Integer.parseInt(Balance_text.getText());
            Integer n = ThreadLocalRandom.current().nextInt(1000,9999);
            PIN_text.setText(n.toString());
            email=Email_text.getText();
            String query1="insert into userdata values('"+user+"',"+Integer.parseInt(PIN_text.getText())+","+bal+",'"+email+"',0)";
            try {
                 LoginPage.st.executeUpdate(query1);
            } catch (SQLException ex) {
                Logger.getLogger(Create_User.class.getName()).log(Level.SEVERE, null, ex);
            }
            javax.swing.JOptionPane.showMessageDialog(rootPane, "User successfully created.", "Success", getDefaultCloseOperation());
            Username_text.setText("Enter Username");
            Balance_text.setText("Enter Balance");
            PIN_text.setText("Enter Password");
            Email_text.setText("Enter email");
        }
    }//GEN-LAST:event_Create_UserActionPerformed

    private void PIN_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PIN_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PIN_textActionPerformed

    private void Username_textFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Username_textFocusGained
        if(Username_text.getText().equals("Enter Username"))
            Username_text.setText("");
    }//GEN-LAST:event_Username_textFocusGained

    private void Username_textFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Username_textFocusLost
        if(Username_text.getText().equals(""))
            Username_text.setText("Enter Username");
    }//GEN-LAST:event_Username_textFocusLost

    private void Balance_textFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Balance_textFocusGained
        if(Balance_text.getText().equals("Enter Balance"))
            Balance_text.setText("");
    }//GEN-LAST:event_Balance_textFocusGained

    private void Balance_textFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Balance_textFocusLost
        if(Balance_text.getText().equals(""))
            Balance_text.setText("Enter Balance");
    }//GEN-LAST:event_Balance_textFocusLost

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
       new admin_page().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BackActionPerformed

    private void Balance_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Balance_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Balance_textActionPerformed

    private void Username_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Username_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Username_textActionPerformed

    private void ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetActionPerformed
        Username_text.setText("Enter Username");
        Balance_text.setText("Enter Balance");
        PIN_text.setText("Enter Password");
    }//GEN-LAST:event_ResetActionPerformed

    private void Email_textFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Email_textFocusGained
        if(Email_text.getText().equals("Enter email"))
            Email_text.setText("");
    }//GEN-LAST:event_Email_textFocusGained

    private void Email_textFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Email_textFocusLost
        if(Email_text.getText().equals(""))
            Email_text.setText("Enter email");
    }//GEN-LAST:event_Email_textFocusLost

    /**
     * @param args the command line arguments
     */
    /*public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
/*        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Create_User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Create_User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Create_User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Create_User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
       /* java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Create_User().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JTextField Balance_text;
    private javax.swing.JButton Cancel;
    private javax.swing.JButton Create_User;
    private javax.swing.JTextField Email_text;
    private javax.swing.JTextField PIN_text;
    private javax.swing.JButton Reset;
    private javax.swing.JTextField Username_text;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
