package admin_pack;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javaapplication2.LoginPage;
import javax.swing.JButton;
import javax.swing.JScrollBar;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import java.awt.Font;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import javax.swing.JTable;
import javax.swing.JScrollPane;
import javax.swing.ScrollPaneConstants;

public class View_User_Details extends javax.swing.JFrame {

    /**
     * Creates new form View_Users
     */
	
	String[] columns = {
			"Username",
			"First Name",
			"Last Name",
			"E-Mail",
			"Account Number",
			"Account Balance"
	};
    public View_User_Details() {
        initComponents();
    }
    Object[][] data = {
    		{"shibashism","Shibashis","Mallik","shibashismallik@gmail.com","12232781237128","Rs. 12000"}
    };
    
    public void fillTable(){
    	/*try {
			ResultSet rs = LoginPage.st.executeQuery("select username from userdata");
			while(rs.next()){*/
				/**
				 * Add the respective columns in JTable in the following format
				 * Object[][] data = {
				 * {"Kathy", "Smith",
				 * "Snowboarding", new Integer(5), new Boolean(false)},
				 * {"John", "Doe",
				 * "Rowing", new Integer(3), new Boolean(true)},
				 * {"Sue", "Black",
				 * "Knitting", new Integer(2), new Boolean(false)},
				 * {"Jane", "White",
				 * "Speed reading", new Integer(20), new Boolean(true)},
				 * {"Joe", "Brown",
				 * "Pool", new Integer(10), new Boolean(false)}
				 * };
				 */
			/*}
		} catch (SQLException e) {
			e.printStackTrace();
		}*/
    	
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        Exit = new javax.swing.JButton();
        Back = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        System.out.println("Hello");

        Exit.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        Exit.setText("Exit");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });

        Back.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        Back.setText("Back");
        Back.setToolTipText("Click here to go back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        
        JButton ViewUserList = new JButton("View User List");
        ViewUserList.setToolTipText("Get the list of users in this bank");
        ViewUserList.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent arg0) {
        		DetailedView(arg0);
        	}
        });
        ViewUserList.setFont(new Font("Trebuchet MS", Font.BOLD, 18));

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        jLabel1.setText("SBM ©");
        jLabel1.setToolTipText("Copyright");
        
        scrollPane = new JScrollPane();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(layout.createSequentialGroup()
        			.addGap(100)
        			.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        				.addComponent(scrollPane, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 692, Short.MAX_VALUE)
        				.addGroup(layout.createSequentialGroup()
        					.addComponent(Back, GroupLayout.PREFERRED_SIZE, 179, GroupLayout.PREFERRED_SIZE)
        					.addGap(67)
        					.addComponent(ViewUserList, GroupLayout.PREFERRED_SIZE, 204, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
        					.addComponent(Exit, GroupLayout.PREFERRED_SIZE, 170, GroupLayout.PREFERRED_SIZE)))
        			.addGap(148))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(layout.createSequentialGroup()
        			.addGap(54)
        			.addComponent(scrollPane, GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE)
        			.addGap(38)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE, false)
        				.addComponent(Back, GroupLayout.PREFERRED_SIZE, 42, GroupLayout.PREFERRED_SIZE)
        				.addComponent(Exit, GroupLayout.PREFERRED_SIZE, 42, GroupLayout.PREFERRED_SIZE)
        				.addComponent(ViewUserList, GroupLayout.PREFERRED_SIZE, 43, GroupLayout.PREFERRED_SIZE))
        			.addGap(33))
        );
        
        UserDetail = new JTable(data, columns);
        scrollPane.setViewportView(UserDetail);
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        System.out.println("Session closed by admin");
        System.exit(0);
    }//GEN-LAST:event_ExitActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        new admin_page().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BackActionPerformed
    
    private void DetailedView(ActionEvent evt){
    	/**
    	 * This function will show all the details from the UserInfo table.
    	 */
    	new admin_pack.View_Users_List().setVisible(true);
    	this.dispose();
    }

    /**
     * @param args the command line arguments
     */
   /* public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
/*        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View_Users.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View_Users.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View_Users.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View_Users.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
       /* java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View_Users().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton Exit;
    private javax.swing.JLabel jLabel1;
    private JScrollPane scrollPane;
    private JTable UserDetail;
}
